version: 0.2

phases:
  pre_build:
    commands:
      - echo "Granting execute permissions to gradlew..."
      - chmod +x ./gradlew
  build:
    commands:
      - echo "Starting gradle build..."
      - ./gradlew build
      - echo "Gradle build finished successfully!"
